# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#4FD675"
color_secondary = "#4fc3d6"
text_color = "#555"
text_dark = "#333"
text_light = "#777"
body_color = "#fff"
border_color = "#EBEBEB"
black = "#000"
white = "#fff"
light = "#F9F9F9"

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.2" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Nunito Sans:wght@400;500;600"
font_primary = "Nunito Sans:ital,wght@0,400;0,600;0,700;0,800;1,800"
font_primary_type = "sans-serif" # [serif/sans-serif]
font_secondary = ""
font_secondary_type = "" # [serif/sans-serif]
font_icon = "Font Awesome 6 Free"


############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/regular.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"

# JS Plugins
# [[params.plugins.js]]
# link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.js]]
link = "plugins/glightbox.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/lazy-loader.js"
[[params.plugins.js]]
link = "https://cpwebassets.codepen.io/assets/embed/ei.js"
attributes = "async"
